### PR TITLE
Adding CoMD Proxy Application

### PR DESCRIPTION
**Pull request by davideberius**
This PR adds the CoMD proxy application with support for MPI runs with threading support for CUDA and OpenMP through RAJA.  The supported configurations are: serial, MPI, CUDA, OpenMP, MPI+CUDA, and MPI+OpenMP.

### CODE REVIEW

**Comment by davideberius** [comment]
This PR requires that the RAJA version be updated to the latest develop branch in the GPU case due to an issue with RAJA that would fail to launch CUDA kernels for some kernels that had high register pressure.

**Comment by davideberius** [comment]
So, it looks like there were two main problems that were happening with the travis tests:
1.) RAJA version mismatch -> kripke requires 0.6.0, CoMD requires develop
2.) The CMakeLists.txt in CoMD was checking for MPI regardless of whether ENABLE_MPI was set

I added a fix for the second problem locally, but the first seems like it will be a little trickier to deal with...

**Comment by rhornung67** [comment]
@davideberius Kripke needs to be updated to use the latest RAJA version. It looks like this is still breaking all the tests....

**Comment by ajkunen** [comment]
@davideberius @rhornung67 I'm working on Kripke today, I'll post an update once it's ready.

**Comment by rhornung67** [comment]
Thanks @ajkunen 🥇

**Pull request closed without merging**
