### PR TITLE
Update to RAJA v0.14.1

### PR DESCRIPTION
**Pull request by rchen20**
- (Will create issue) Bug in new build scripts: Enabling OpenMP on CUDA builds adds extra `-fopenmp` to the nvcc link line, causing an unrecognized parameter failure. Current workaround is to disable OpenMP on CUDA builds.
- [x] Need CAMP v0.2.3 for `stdexcept` error with clang.
- [x] Update Kripke. (Need to accept 1 change, and merge kripke/feature/rajaHIP into kripke/develop.)
- [x] Incorporate `-DBLT_CXX_STD=c++14` for building Kripke.
- [x] Try other compilers (done so far: nvcc10.1.243 + gcc8.3.1 + clang-ibm/11.0.1 + xl/2021.03.11, openmp xl/2021.03.11).
- [x] Kripke resource error with device memory. For CUDA, this occurs when ATS is disabled. Preliminary solution here https://github.com/LLNL/Kripke/pull/32/. Real culprit is fixed here https://github.com/LLNL/RAJA/pull/1133.
- [x] Update build scripts.
- [x] Update COMD.
- [x] Update to RAJA v0.14.0.
- [x] Update Lulesh 1.0 to use Typed segments.
- [x] Update Lulesh 2.0 to use Typed segments.
- [x] Fix Lulesh 2.0 cuda problem https://github.com/LLNL/RAJAProxies/issues/22.

### CODE REVIEW

**Comment by rhornung67** [comment]
@rchen20 several comments on this PR:

- Please consider updating the segment types to to use the "Typed" variants; e.g., TypedListSegment, etc. and insert the proper index value type as a template parameter. This may help users be more clear about RAJA usage. The segment type change affects lulesh-init.cpp and lulesh.hpp files.
- A resource must be passed to all TypedListSegment ctor calls. So this change is not a complete fix.
- Similar changes are required for LULESH 1.0.

**Comment by rchen20** [comment]
@rhornung67 These should be fixed now in both Luleshes.
> * Please consider updating the segment types to to use the "Typed" variants; e.g., TypedListSegment, etc. and insert the proper index value type as a template parameter. This may help users be more clear about RAJA usage. The segment type change affects lulesh-init.cpp and lulesh.hpp files.
> * A resource must be passed to all TypedListSegment ctor calls. So this change is not a complete fix.
> * Similar changes are required for LULESH 1.0.

**Review by rhornung67 — APPROVED** [review]
Looks good. Thanks @rchen20 

Did you run everything locally on multiple platforms. We don't have any CI set up for this repo.

**Comment by rchen20** [comment]
@rhornung67 This is not quite ready yet; still working on the Kripke Camp issue, and have not tried COMD yet. After those, I'll try everything out on multiple platforms (only using NVCC + GCC at the moment).

**Pull request merged**
