### PR TITLE
Adding CoMD Proxy Application

### PR DESCRIPTION
**Pull request by davideberius**
This PR adds the CoMD proxy application with support for MPI runs with threading support for CUDA and OpenMP through RAJA. The supported configurations are: serial, MPI, CUDA, OpenMP, MPI+CUDA, and MPI+OpenMP.

### CODE REVIEW

**Comment by rhornung67** [comment]
Can we get a few folks to look at this and review?

**Review by pearce8 — APPROVED** [review]
This is the same as PR #17 which has been approved previously.  The only change is fixing the automatic tests.

**Review by rhornung67 — APPROVED** [review]
Thanks @davideberius

**Comment by rhornung67** [comment]
@davidbeckingsale when you have time, please review this PR before we merge it.

**Comment by davideberius** [comment]
Once this has been reviewed, I plan to squash the commits into more manageable commit messages rather than the mess it is now.

**Comment by davidbeckingsale** [comment]
I think this looks reasonable. My only question is whether we could use BLT to handle the MPI stuff, rather than the handcoded CMake?

**Comment by pearce8** [comment]
@davidbeckingsale I'll put that on my to do list but realistically I won't get to it right away.  Can we proceed with the merge as is?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale I'll put that on my to do list but realistically I won't get to it right away. Can we proceed with the merge as is?

Okay.

**Comment by pearce8** [comment]
@davidbeckingsale Awesome, thanks!  I am not authorized to merge - how should we proceed?  

@davideberius Can you please try to squash the commits now?

**Comment by davidbeckingsale** [comment]
@davideberius - if you don't want to rebase the commits, I can just do a "squash merge" which will create a single commit for this.

**Comment by davideberius** [comment]
@davidbeckingsale for the squash merge, will the commit message just concatenate all of the commit messages?

**Comment by davidbeckingsale** [comment]
The message can be edited.

**Comment by davideberius** [comment]
I see, in that case, that might be the best option.  Do you think the PR message above is sufficient?

"This PR adds the CoMD proxy application with support for MPI runs with threading support for CUDA and OpenMP through RAJA. The supported configurations are: serial, MPI, CUDA, OpenMP, MPI+CUDA, and MPI+OpenMP."

**Comment by davidbeckingsale** [comment]
Done!

**Comment by rhornung67** [comment]
Thanks @davideberius

**Comment by pearce8** [comment]
Thanks, @davideberius and @davidbeckingsale!

**Pull request merged**
