### PR TITLE
Updates to RAJA, CHAI v2022.03.0, Umpire v2022.03.1.

### PR DESCRIPTION
**Pull request by rchen20**
One slight caveat is that we need to pass `-DRAJA_ENABLE_OPENMP=Off` to cmake to make sure OpenMP is off.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Hey @rchen20 can you elaborate on the caveat? You should be able to do:
`set(RAJA_ENABLE_OPENMP Off CACHE BOOL "")`
in the CMake somewhere to have this be the "default", but still overridable on the command line.

**Comment by rhornung67** [comment]
@davidbeckingsale I think the problem may be that in RAJA, before my recent PR merge which occurred after the v2022.03.00 release, we were setting OpenMP to on in two places, in the dependent options file and in the cache in another file.

**Comment by rchen20** [comment]
@rhornung67 is correct, it's that RAJA's CMakeLists.txt is setting `RAJA_ENABLE_OPENMP=On` by default, and the only way to prevent this is to override this on the command line. I don't think it's worth patching RAJA to fix this, but I guess I could add this to every build script.

**Comment by rhornung67** [comment]
@rchen20 this is fixed in RAJA develop, if you want to move to that. If you do, there's no need to change the build scripts.

**Comment by rhornung67** [comment]
@rchen20 please add an issue to add CI to this project.  We can do that at some point when we have time.  Then, we can add some cross-project CI so that when RAJA develop changes, for example, we can run CI on this. It will be easier to catch breakages and keep things up-to-date.

**Comment by rchen20** [comment]
@davidbeckingsale @rhornung67 This is ready for approval, please take a look when you can.

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
